'use client';
import {useEffect,useMemo,useState} from 'react';
import {loadLocalCase,saveLocalCase,removeLocalCase} from '@/lib/local-case';
import {HeartHandshake,ShieldCheck,FileText,LifeBuoy,Users,LockKeyhole,BookOpen,Download,Copy,Check,ChevronLeft,Search,Wallet,Bookmark,Printer,Phone,ExternalLink,Plus,Home,Menu,X,CheckCircle2} from 'lucide-react';
import {RadioGroup,RadioGroupItem} from '@/components/ui/radio-group';
import {Checkbox} from '@/components/ui/checkbox';
import {Progress} from '@/components/ui/progress';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Sheet,SheetContent,SheetTitle,SheetDescription} from '@/components/ui/sheet';
import {Answers,emptyAnswers,choices,answerLabel,generatePlan,Step,articles,Article,sources,SavedCase,buildDraft,steps} from '@/lib/bereg';

type View='home'|'intake'|'plan'|'materials'|'case'|'helper'|'protect'|'check';
const views:View[]=['home','intake','plan','materials','case','helper','protect','check'];
const titles=['Сначала — безопасность','Что произошло','Как потеря повлияла на вас','Что уже удалось сделать','Как вы сейчас'];
const groupLabels=['Безопасность','Ситуация','Последствия','Ваши действия','Поддержка'];
const supportCopy='Со мной произошёл обман. Мне тяжело, и мне нужна поддержка без осуждения. Пожалуйста, побудь рядом и помоги разобраться с ближайшим шагом.';
function Brand({small=false}:{small?:boolean}){return <span className={`brand ${small?'small':''}`}><img src="./favicon.svg" alt=""/><span>Берег</span></span>}
function Wave({tone='green'}:{tone?:string}){return <svg className={`wave wave-${tone}`} viewBox="0 0 600 300" preserveAspectRatio="none" aria-hidden="true"><path className="wave-back" d="M0 70C170-30 230 240 600 20V300H0Z"/><path className="wave-gap" d="M0 170C150 30 280 300 600 80V300H0Z"/><path className="wave-front" d="M0 202C170 80 285 320 600 115V300H0Z"/></svg>}
function SourceLink({source}:{source:{label:string;url:string}}){return <a className="source-link" href={source.url} target="_blank" rel="noopener noreferrer"><BookOpen size={17}/><span>{source.label}</span><ExternalLink size={14}/></a>}
function Choice({field,label,answers,setAnswers}:{field:keyof typeof choices;label:string;answers:Answers;setAnswers:(a:Answers)=>void}){return <fieldset className="question-field"><legend>{label}</legend><RadioGroup value={String(answers[field])} onValueChange={v=>setAnswers({...answers,[field]:v})} className="choices">{choices[field].map(([value,text])=><label className={`choice ${answers[field]===value?'selected':''}`} key={value}><RadioGroupItem value={value}/><span>{text}</span></label>)}</RadioGroup></fieldset>}
function download(name:string,text:string){const url=URL.createObjectURL(new Blob(['\ufeff'+text],{type:'text/plain;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),500)}

export default function BeregApp(){
 const [view,setView]=useState<View>('home');const [answers,setAnswers]=useState<Answers>({...emptyAnswers});const [question,setQuestion]=useState(0);const [role,setRole]=useState<'self'|'helper'>('self');
 const [activeStep,setActiveStep]=useState<Step|null>(null);const [activeArticle,setActiveArticle]=useState<Article|null>(null);const [support,setSupport]=useState(false);const [supportPart,setSupportPart]=useState(0);const [urgent,setUrgent]=useState(false);const [menu,setMenu]=useState(false);
 const [documents,setDocuments]=useState<Record<string,string>>({});const [draftType,setDraftType]=useState<'bank'|'police'|null>(null);const [draftText,setDraftText]=useState('');const [saved,setSaved]=useState<SavedCase|null>(null);const [saveBusy,setSaveBusy]=useState(false);const [caseLoading,setCaseLoading]=useState(true);const [caseError,setCaseError]=useState('');const [notice,setNotice]=useState('');
 const [search,setSearch]=useState('');const [filter,setFilter]=useState('Все материалы');const [checkedSigns,setCheckedSigns]=useState<string[]>([]);const [signsResult,setSignsResult]=useState(false);const [focusStep,setFocusStep]=useState<string|null>(null);
 const plan=useMemo(()=>generatePlan(answers),[answers]);const hasPlan=!!answers.kind&&!!answers.mood;
 function go(next:View){setView(next);setMenu(false);setActiveArticle(null);setActiveStep(null);if(typeof window!=='undefined'){const url=new URL(window.location.href);url.searchParams.delete('view');if(next!=='home')url.searchParams.set('view',next);url.hash='';window.history.pushState({},'',url.pathname+url.search);window.scrollTo({top:0,behavior:'instant'})}}
 function start(helper=false){setRole(helper?'helper':'self');setQuestion(0);go('intake')}
 function flash(text:string){setNotice(text);setTimeout(()=>setNotice(''),4500)}
 async function copy(text:string){try{await navigator.clipboard.writeText(text);flash('Текст скопирован')}catch{flash('Не получилось скопировать. Можно выделить текст вручную.')}}
 async function loadCase(){setCaseLoading(true);setCaseError('');try{setSaved(loadLocalCase())}catch(e){setCaseError(e instanceof Error?e.message:'Не получилось загрузить случай.')}finally{setCaseLoading(false)}}
 async function saveCase(docs=documents,focus=focusStep){if(!hasPlan){start();return}setSaveBusy(true);setCaseError('');try{setSaved(saveLocalCase({answers,documents:docs,focusStep:focus}));flash('Случай сохранён в этом браузере.')}catch(e){setCaseError(e instanceof Error?e.message:'Не удалось сохранить случай.');flash('Не удалось сохранить. Ответы остаются на экране.')}finally{setSaveBusy(false)}}
 function deleteCase(){try{removeLocalCase();setSaved(null);setDocuments({});setAnswers({...emptyAnswers,already:[]});setFocusStep(null);setCaseError('');flash('Сохранённый случай удалён из этого браузера.')}catch{setCaseError('Не удалось удалить случай. Проверьте настройки браузера.')}}
 function openStep(step:Step){setActiveStep(step);setFocusStep(step.id)}
 function openSaved(){if(!saved)return;setAnswers(saved.answers);setDocuments(saved.documents);setFocusStep(saved.focusStep);go('plan')}
 function openDraft(type:'bank'|'police'){setDraftType(type);setDraftText(documents[type]||buildDraft(type,answers))}
 async function saveDraft(){if(!draftType)return;const next={...documents,[draftType]:draftText};setDocuments(next);if(hasPlan)await saveCase(next);else flash('Черновик подготовлен. Его можно скачать.');}
 useEffect(()=>{const read=()=>{const v=new URLSearchParams(window.location.search).get('view') as View;setView(views.includes(v)?v:'home')};read();window.addEventListener('popstate',read);void loadCase();return()=>window.removeEventListener('popstate',read)},[]);
 useEffect(()=>{const context=(document as unknown as {modelContext?:{registerTool:(tool:unknown,options:unknown)=>unknown}}).modelContext;if(!context?.registerTool)return;const lifecycle=new AbortController();for(const tool of [{name:'get_current_bereg_plan',title:'Посмотреть текущий план',description:'Read the current unsaved answers and plan visible on the page. Does not access saved cases.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute:(input:unknown)=>{if(!input||typeof input!=='object'||Object.keys(input).length)throw new Error('Expected empty object');return {available:hasPlan,steps:hasPlan?plan.map(s=>({id:s.id,title:s.title,category:s.category})):[]}}},{name:'start_bereg_questionnaire',title:'Начать описание случая',description:'Navigate to the case questionnaire. Does not submit or save any data.',inputSchema:{type:'object',properties:{role:{type:'string',enum:['self','helper']}},required:['role'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute:(input:unknown)=>{const data=input as {role?:string};if(!data||!['self','helper'].includes(data.role||'')||Object.keys(data).some(k=>k!=='role'))throw new Error('Invalid role');start(data.role==='helper');return {view:'intake',question:1}}}]){try{void Promise.resolve(context.registerTool(tool,{signal:lifecycle.signal})).catch(()=>{})}catch{}}return()=>lifecycle.abort()},[hasPlan,plan]);
 const canContinue=question===0?!!answers.risk&&!!answers.timing:question===1?!!answers.kind&&!!answers.money:question===2?!!answers.impact&&!!answers.amount:question===3?true:!!answers.mood&&!!answers.support;
 const filtered=articles.filter(a=>(filter==='Все материалы'||a.tag===filter)&&`${a.title} ${a.summary}`.toLowerCase().includes(search.toLowerCase()));
 return <div className="app-shell">
 <a className="skip-link" href="#main">Перейти к содержанию</a>
 <header className="site-header"><button className="brand-button" onClick={()=>go('home')} aria-label="Берег — главная"><Brand/></button><nav className={menu?'open':''} aria-label="Основная навигация"><button className={view==='home'||view==='intake'||view==='plan'?'active':''} onClick={()=>go('home')}>Получить помощь</button><button className={view==='materials'?'active':''} onClick={()=>go('materials')}>Материалы</button><button className={view==='case'?'active':''} onClick={()=>go('case')}>Мой случай</button></nav><button className="support-header" onClick={()=>setSupport(true)}><HeartHandshake size={19}/><span>Мне сейчас тяжело</span></button><button className="mobile-menu" onClick={()=>setMenu(!menu)} aria-label={menu?'Закрыть меню':'Открыть меню'}>{menu?<X/>:<Menu/>}</button></header>
 <main id="main" className={`main-content view-${view}`}>
 {view==='home'&&<>
 <div className="home-topline"><span className="eyebrow">Помощь после мошенничества</span><span className="quiet-label"><LockKeyhole size={14}/>Начать можно без регистрации</span></div>
 <section className="intro-grid"><div className="intro-copy"><h1>Разберёмся,<br/>что делать <span className="highlight-word">дальше.</span></h1><p>Когда произошёл обман, не нужно справляться со всем сразу. Поможем найти опору и выбрать ближайший шаг.</p><div className="intro-actions"><button className="button primary large" onClick={()=>start()}><LifeBuoy size={21}/>Меня обманули</button><button className="text-button" onClick={()=>go('helper')}>Помогаю близкому</button></div><div className="intro-note"><Check size={15}/>Без осуждения. В вашем темпе.</div></div><div className="shore-card"><div className="shore-top"><span className="pill">Один шаг за раз</span><img src="./favicon.svg" alt=""/></div><p className="shore-title">После обмана<br/>есть <span>дальше.</span></p><Wave/><span className="shore-foot">Берег рядом</span></div></section>
 <button className="urgent-strip" onClick={()=>setUrgent(true)}><span className="urgent-icon"><ShieldCheck size={23}/></span><span><strong>Есть риск новых списаний?</strong><span>Первые действия доступны сразу, без опроса.</span></span><span className="urgent-link">Что сделать сейчас</span></button>
 <section className="journey-section"><div className="section-heading"><h2>От растерянности — к понятным действиям</h2><span className="subtle">Помощь на каждом этапе</span></div><div className="journey-grid">{[{n:'01',icon:HeartHandshake,title:'Найти опору',text:'Пауза, спокойный разговор и поддержка, когда трудно собраться.',tone:'green',action:()=>setSupport(true)},{n:'02',icon:FileText,title:'Разобраться со случаем',text:'План по вашей ситуации, инструкции и черновики обращений.',tone:'lime',action:()=>start()},{n:'03',icon:ShieldCheck,title:'Двигаться дальше',text:'Посильные шаги для восстановления и защиты от повторного обмана.',tone:'blue',action:()=>go('protect')}].map(item=><button key={item.n} className={`journey-card ${item.tone}`} onClick={item.action}><span className="journey-top"><item.icon size={24}/><span>{item.n}</span></span><h3>{item.title}</h3><p>{item.text}</p><span className="card-link">Подробнее<Plus size={17}/></span></button>)}</div></section>
 <section className="materials-preview"><div className="section-heading"><h2>На что можно опереться</h2><button className="text-button" onClick={()=>go('materials')}>Все материалы</button></div><div className="article-grid">{articles.slice(0,3).map(a=><ArticleCard key={a.id} article={a} onClick={()=>setActiveArticle(a)}/>)}</div></section>
 <div className="secondary-entries"><button onClick={()=>go('check')}><Search size={20}/><span>Не уверен(а), что произошёл обман</span><Plus size={17}/></button><button onClick={()=>go('protect')}><ShieldCheck size={20}/><span>Хочу защититься</span><Plus size={17}/></button></div>
 </>}
 {view==='intake'&&<><button className="back-link" onClick={()=>question>0?setQuestion(question-1):go('home')}><ChevronLeft size={18}/>{question>0?'Предыдущий шаг':'На главную'}</button><div className="intake-layout"><aside className="intake-aside"><span className="eyebrow">Ваш персональный план</span><h1>Начнём<br/>с вашей<br/><span>ситуации.</span></h1><p>{role==='helper'?'Отвечайте вместе с близким и с его согласия. Не нужно знать все подробности сразу.':'Несколько вопросов помогут выбрать подходящие действия. Здесь не нужны реквизиты и пароли.'}</p><ol className="intake-track">{groupLabels.map((l,i)=><li key={l} className={i===question?'current':i<question?'past':''}><span>{i<question?<Check size={14}/>:i+1}</span>{l}</li>)}</ol><div className="aside-support"><HeartHandshake size={24}/><p>Можно сделать паузу<br/>в любой момент.</p><button className="text-button" onClick={()=>setSupport(true)}>Мне нужна поддержка</button></div></aside><section className="question-panel"><div className="question-progress"><span>Шаг {question+1} из 5</span><span>Около 3–5 минут</span></div><Progress value={(question+1)*20} aria-label="Ход опроса"/><h2>{titles[question]}</h2><p className="question-description">{['Проверим, могут ли посторонние продолжать пользоваться вашими доступами.','Выберите наиболее похожий вариант. Подробности можно добавить позже.','Сумма потери важна относительно вашей жизни. Точная цифра не обязательна.','Отметьте подходящее. Если ещё ничего — просто продолжайте.','Поддержка поможет пройти следующие шаги в подходящем темпе.'][question]}</p>
 {question===0&&<><Choice field="risk" label="У посторонних мог остаться доступ к деньгам или аккаунтам?" answers={answers} setAnswers={setAnswers}/>{answers.risk&&answers.risk!=='no'&&<div className="inline-callout"><ShieldCheck size={20}/><div><strong>Сначала можно защитить доступы</strong><button className="text-button" onClick={()=>setUrgent(true)}>Открыть первые действия</button></div></div>}<Choice field="timing" label="Когда вы обнаружили обман?" answers={answers} setAnswers={setAnswers}/></>}
 {question===1&&<><Choice field="kind" label="Что произошло?" answers={answers} setAnswers={setAnswers}/><Choice field="money" label="Какие деньги были потеряны?" answers={answers} setAnswers={setAnswers}/></>}
 {question===2&&<><Choice field="impact" label="Что сейчас беспокоит больше всего?" answers={answers} setAnswers={setAnswers}/><Choice field="amount" label="Примерный размер потери" answers={answers} setAnswers={setAnswers}/></>}
 {question===3&&<><fieldset className="question-field"><legend>Какие действия вы уже предприняли?</legend><div className="choices">{choices.already.map(([v,l])=><label className={`choice ${answers.already.includes(v)?'selected':''}`} key={v}><Checkbox checked={answers.already.includes(v)} onCheckedChange={c=>setAnswers({...answers,already:c?[...answers.already,v]:answers.already.filter(x=>x!==v)})}/><span>{l}</span></label>)}</div></fieldset><label className="textarea-label" htmlFor="notes">Хотите добавить описание? <span>Необязательно</span></label><textarea id="notes" rows={5} maxLength={4000} value={answers.notes} onChange={e=>setAnswers({...answers,notes:e.target.value})} placeholder="Коротко опишите, что случилось. Не указывайте пароли, коды и полные реквизиты карты."/><p className="field-note">Это описание можно будет использовать в черновике обращения.</p></>}
 {question===4&&<><Choice field="mood" label="Как вы сейчас себя чувствуете?" answers={answers} setAnswers={setAnswers}/><Choice field="support" label="Есть ли рядом человек, который может поддержать?" answers={answers} setAnswers={setAnswers}/></>}
 <div className="question-controls"><button className="button primary" disabled={!canContinue} onClick={()=>question<4?(setQuestion(question+1),window.scrollTo({top:0,behavior:'instant'})):go('plan')}>{question===4?'Получить мой план':'Продолжить'}</button><span className="field-note">Можно вернуться и изменить ответы</span></div></section></div></>}
 {view==='plan'&&(hasPlan?<><div className="page-head"><div><span className="eyebrow">По вашей ситуации</span><h1>Ваш план действий</h1><p>Начните с ближайшего шага. Остальное можно пройти в своём темпе.</p><p className="field-note">Сохранение доступно только в этом браузере.</p></div><button className="button secondary" disabled={saveBusy} onClick={()=>saveCase()}><Bookmark size={18}/>{saveBusy?'Сохраняем…':'Сохранить мой случай'}</button></div>{caseError&&<p className="error-message" role="alert">{caseError}</p>}<div className="plan-layout"><div className="plan-main"><div className={`next-step ${plan[0].tone}`}><div><span className="pill">Ближайший шаг</span><h2>{plan[0].title}</h2><p>{plan[0].summary}</p><button className="button primary" onClick={()=>openStep(plan[0])}>Начать с этого</button></div><LifeBuoy size={86} strokeWidth={1}/></div><div className="section-heading"><h2>Дальнейшие действия</h2><span className="subtle">{plan.length-1} шагов</span></div><div className="plan-list">{plan.slice(1).map((s,i)=><button className="plan-item" key={s.id} onClick={()=>openStep(s)}><span className={`step-number ${s.tone}`}>{String(i+2).padStart(2,'0')}</span><span className="step-copy"><span className="step-category">{s.category}</span><strong>{s.title}</strong><span>{s.summary}</span></span><Plus size={20}/></button>)}</div></div><aside className="plan-aside"><div className="summary-card"><span className="eyebrow">Учитываем ваши ответы</span><h3>Ваш случай</h3><p>{answerLabel('kind',answers.kind)}</p><dl><dt>Когда обнаружили</dt><dd>{answerLabel('timing',answers.timing)}</dd><dt>Главное последствие</dt><dd>{answerLabel('impact',answers.impact)}</dd></dl><button className="text-button" onClick={()=>{setQuestion(0);go('intake')}}>Изменить ответы</button></div><div className="support-side"><HeartHandshake size={30}/><h3>Не обязательно<br/>справляться одному.</h3><p>Поддержка доступна на любом шаге.</p><button className="button light" onClick={()=>setSupport(true)}>Сделать паузу</button></div><button className="print-link" onClick={()=>download('bereg-plan.txt',plan.map((s,i)=>`${i+1}. ${s.title}\n${s.actions.join('\n')}\n${s.source?.url||''}`).join('\n\n'))}><Download size={16}/>Скачать план</button></aside></div></>:<EmptyState title="Сначала расскажите о ситуации" text="Ответьте на несколько вопросов, чтобы получить подходящий план." action="Начать описание" onClick={()=>start()}/>)}
 {view==='materials'&&<><div className="page-head"><div><span className="eyebrow">Библиотека поддержки</span><h1>Понятно о важном</h1><p>Короткие материалы, к которым можно вернуться в любой момент.</p></div></div><div className="materials-controls"><div className="search-field"><Search size={20}/><input aria-label="Поиск материалов" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Что вы хотите узнать?"/>{search&&<button onClick={()=>setSearch('')} aria-label="Очистить поиск"><X size={17}/></button>}</div><div className="filter-row" role="group" aria-label="Темы материалов">{['Все материалы','Первые действия','Поддержка','Финансовая помощь','Юридическая помощь','Защита','Близким'].map(f=><button key={f} aria-pressed={filter===f} className={filter===f?'selected':''} onClick={()=>setFilter(f)}>{f}</button>)}</div></div>{filtered.length?<div className="article-grid full">{filtered.map(a=><ArticleCard key={a.id} article={a} onClick={()=>setActiveArticle(a)}/>)}</div>:<EmptyState title="Ничего не нашлось" text="Попробуйте другой запрос или выберите все материалы." action="Сбросить поиск" onClick={()=>{setSearch('');setFilter('Все материалы')}}/>}<div className="official-note"><BookOpen size={19}/><span>В материалах есть ссылки на первоисточники: Банк России и официальные службы помощи.</span></div></>}
 {view==='case'&&<><div className="page-head"><div><span className="eyebrow">Всё в одном месте</span><h1>Мой случай</h1><p>Ваши ответы, план и подготовленные черновики.</p></div></div><div className="official-note"><LockKeyhole size={19}/><span>Случай сохраняется только в этом браузере. На другом устройстве он недоступен. Очистка данных браузера удалит сохранение. На общем устройстве удалите случай после работы.</span></div>{caseLoading?<div className="empty-state"><LifeBuoy className="spinner" size={40}/><h2>Загружаем ваш случай…</h2></div>:caseError?<><EmptyState title="Не получилось загрузить" text={caseError} action="Попробовать снова" onClick={()=>loadCase()}/><button className="text-button" onClick={deleteCase}>Удалить сохранение из этого браузера</button></>:saved?<div className="case-grid"><section className="saved-case-card"><span className="pill">Сохранённый случай</span><h2>{answerLabel('kind',saved.answers.kind)}</h2><p>{answerLabel('impact',saved.answers.impact)}</p><div className="case-meta"><span>Обновлено {new Date(saved.updatedAt).toLocaleDateString('ru-RU')}</span><span>{generatePlan(saved.answers).length} шагов в плане</span></div><button className="button primary" onClick={openSaved}>Вернуться к плану</button><button className="text-button" onClick={deleteCase}>Удалить сохранённый случай</button>{saved.focusStep&&steps[saved.focusStep]&&<p className="field-note">Последний открытый шаг: {steps[saved.focusStep].title}</p>}</section><section className="documents-card"><FileText size={27}/><h2>Ваши черновики</h2>{Object.keys(saved.documents).length?Object.entries(saved.documents).map(([type,text])=><div className="document-row" key={type}><span>{type==='bank'?'Обращение в банк':'Заявление в полицию'}</span><button aria-label="Скачать черновик" onClick={()=>download(`bereg-${type}.txt`,text)}><Download size={19}/></button><button onClick={()=>{setAnswers(saved.answers);setDocuments(saved.documents);setDraftType(type as 'bank'|'police');setDraftText(text)}}>Открыть</button></div>):<p>Здесь появятся черновики, которые вы подготовите и сохраните в шагах плана.</p>}</section></div>:<EmptyState title="Здесь будет ваш случай" text={hasPlan?'Ваш план уже готов. Сохраните его, чтобы вернуться позже.':'Начните с короткого описания ситуации. После опроса можно сохранить план и материалы.'} action={hasPlan?'Сохранить мой случай':'Начать описание'} onClick={()=>hasPlan?saveCase():start()}/>} </>}
 {view==='helper'&&<><div className="editorial-intro"><span className="eyebrow">Для близких</span><h1>Быть рядом —<br/>уже <span>помощь.</span></h1><p>Не нужно знать все ответы. Можно поддержать человека и вместе разобраться с ближайшим действием.</p><button className="button primary" onClick={()=>start(true)}><Users size={19}/>Пройти опрос вместе</button></div><div className="helper-grid">{[{title:'Сначала выслушайте',text:'Спросите, что нужно сейчас. Не торопите и не требуйте рассказать всё сразу.'},{title:'Предложите конкретную помощь',text:'Побыть рядом, записать факты или вместе открыть официальный канал банка.'},{title:'Сохраните право выбора',text:'Действуйте с согласия человека. Решения о его деньгах и аккаунтах остаются за ним.'}].map((x,i)=><div className="helper-card" key={x.title}><span className="step-number green">0{i+1}</span><h2>{x.title}</h2><p>{x.text}</p></div>)}</div><div className="message-card"><div><span className="eyebrow">Можно сказать так</span><h2>«Я рядом. Я не буду тебя осуждать.<br/>Давай разберёмся с одним шагом».</h2></div><button className="button secondary" onClick={()=>copy('Я рядом. Я не буду тебя осуждать. Давай разберёмся с одним шагом.')}><Copy size={17}/>Скопировать</button></div><button className="urgent-strip" onClick={()=>setUrgent(true)}><ShieldCheck/><span><strong>Если доступ к деньгам мог остаться у посторонних</strong><span>Помогите близкому открыть первые действия.</span></span><span className="urgent-link">Открыть</span></button></>}
 {view==='protect'&&<><div className="editorial-intro"><span className="eyebrow">Восстановление и защита</span><h1>Вернуть опору.<br/><span>Двигаться дальше.</span></h1><p>Небольшие шаги помогают вернуть контроль над повседневной жизнью и увереннее проверять новые предложения.</p></div><div className="recovery-grid"><button className="recovery-card green" onClick={()=>openStep(steps.restore)}><Wallet size={34}/><h2>Ближайшие расходы</h2><p>Определить важное и составить посильный план.</p><span className="card-link">Открыть памятку<Plus size={18}/></span></button><button className="recovery-card lime" onClick={()=>openStep(steps.protect)}><ShieldCheck size={34}/><h2>Защита от нового обмана</h2><p>Проверять предложения и замечать давление.</p><span className="card-link">Открыть памятку<Plus size={18}/></span></button></div><div className="section-heading"><h2>Особенно важно после потери денег</h2></div><div className="article-grid">{[articles[4],articles[1],articles[2]].map(a=><ArticleCard key={a.id} article={a} onClick={()=>setActiveArticle(a)}/>)}</div></>}
 {view==='check'&&<><div className="editorial-intro"><span className="eyebrow">Если пока не уверены</span><h1>Проверим,<br/>что <span>настораживает.</span></h1><p>Это ориентиры для проверки ситуации. Они не устанавливают факт мошенничества.</p></div><section className="check-panel"><h2>Что происходило?</h2><div className="choices">{[['rush','Торопили и не давали проверить информацию'],['codes','Просили коды, пароли или удалённый доступ'],['safe','Предлагали перевести деньги на «безопасный счёт»'],['return','Обещали гарантированный возврат за предоплату'],['identity','Представлялись банком или ведомством без независимого подтверждения']].map(([v,l])=><label key={v} className={`choice ${checkedSigns.includes(v)?'selected':''}`}><Checkbox checked={checkedSigns.includes(v)} onCheckedChange={c=>{setCheckedSigns(c?[...checkedSigns,v]:checkedSigns.filter(x=>x!==v));setSignsResult(false)}}/><span>{l}</span></label>)}</div><button className="button primary" onClick={()=>setSignsResult(true)}>Посмотреть ориентиры</button>{signsResult&&<div className="check-result" role="status"><ShieldCheck size={28}/><h3>{checkedSigns.length?'Есть поводы проверить ситуацию':'Отсутствие этих признаков не исключает обман'}</h3><p>Свяжитесь с организацией по контактам с её официального сайта. Если деньги уже потеряны, можно перейти к описанию случая.</p><button className="button secondary" onClick={()=>start()}>Деньги уже потеряны</button><SourceLink source={sources.protection}/></div>}</section></>}
 </main>
 <footer className="site-footer"><button className="brand-button" onClick={()=>go('home')}><Brand small/></button><span>Опора после обмана.</span><div><button onClick={()=>go('materials')}>Материалы</button><button onClick={()=>setSupport(true)}>Получить поддержку</button></div></footer>
 <button className="floating-support" onClick={()=>setSupport(true)} aria-label="Открыть эмоциональную поддержку"><HeartHandshake size={23}/></button>
 {notice&&<div className="toast" role="status"><CheckCircle2 size={19}/>{notice}</div>}
 <Dialog open={support} onOpenChange={v=>{setSupport(v);if(!v)setSupportPart(0)}}><DialogContent className="support-dialog"><span className="dialog-symbol"><HeartHandshake size={34}/></span><DialogTitle className="dialog-title">Сейчас можно сделать паузу.</DialogTitle><DialogDescription>Не нужно решать всё за один раз. Начните с небольшого действия, которое вам подходит.</DialogDescription><div className="grounding"><span className="eyebrow">{supportPart+1} / 3 · Небольшая пауза</span><h3>{['Почувствуйте опору','Посмотрите вокруг','Выберите один шаг'][supportPart]}</h3><p>{['Если вам удобно, сядьте и почувствуйте опору под ногами. Не нужно заставлять себя успокаиваться.','Заметьте несколько предметов вокруг и мысленно назовите их. Можно выпить воды или побыть в тишине.','Можно попросить близкого побыть рядом, связаться со службой поддержки или вернуться к плану.'][supportPart]}</p><button className="button primary" onClick={()=>supportPart<2?setSupportPart(supportPart+1):setSupport(false)}>{supportPart<2?'Следующий небольшой шаг':'Вернуться к своим действиям'}</button></div><div className="support-links"><button className="text-button" onClick={()=>copy(supportCopy)}><Copy size={16}/>Скопировать сообщение близкому</button><a href="https://psi.mchs.gov.ru/" target="_blank" rel="noopener noreferrer"><ExternalLink size={16}/>Психологическая помощь МЧС</a><a href="tel:+74959895050"><Phone size={16}/>+7 (495) 989-50-50</a></div><p className="emergency-note">При непосредственной угрозе жизни или безопасности — <a href="tel:112">112</a>.</p></DialogContent></Dialog>
 <Dialog open={urgent} onOpenChange={setUrgent}><DialogContent className="urgent-dialog"><span className="dialog-symbol lime"><ShieldCheck size={32}/></span><DialogTitle className="dialog-title">Сначала ограничим дальнейший ущерб.</DialogTitle><DialogDescription>Если у посторонних мог остаться доступ, начните с официальной поддержки банка.</DialogDescription><ol className="numbered-actions">{steps.security.actions.map((s,i)=><li key={s}><span>{i+1}</span><p>{s}</p></li>)}</ol><SourceLink source={sources.bank}/><button className="button primary" onClick={()=>{setUrgent(false);start()}}>Перейти к описанию случая</button></DialogContent></Dialog>
 <Sheet open={!!activeStep||!!activeArticle} onOpenChange={v=>{if(!v){setActiveStep(null);setActiveArticle(null)}}}><SheetContent className="detail-sheet"><span className="eyebrow">{activeStep?.category||activeArticle?.tag}</span><SheetTitle className="sheet-title">{activeStep?.title||activeArticle?.title}</SheetTitle><SheetDescription>{activeStep?.summary||activeArticle?.summary}</SheetDescription>{activeStep&&<><div className="detail-callout"><h3>Зачем этот шаг</h3><p>{activeStep.why}</p></div><h3>Что подготовить</h3><ul className="prepare-list">{activeStep.prepare.map(p=><li key={p}><Check size={16}/>{p}</li>)}</ul><h3>Как действовать</h3><ol className="numbered-actions">{activeStep.actions.map((s,i)=><li key={s}><span>{i+1}</span><p>{s}</p></li>)}</ol>{activeStep.template&&<div className="template-card"><FileText size={26}/><div><h3>Подготовить черновик</h3><p>Дополните текст своими фактами и проверьте его перед отправкой.</p></div><button className="button primary" onClick={()=>openDraft(activeStep.template!)}>Открыть шаблон</button></div>}{activeStep.source&&<SourceLink source={activeStep.source}/>}<div className="sheet-bottom"><button className="button secondary" onClick={()=>{if(hasPlan)saveCase(documents,plan.some(p=>p.id===activeStep.id)?activeStep.id:null);else start()}}><Bookmark size={17}/>{hasPlan?'Сохранить случай с этим шагом':'Составить персональный план'}</button></div></>}{activeArticle&&<><div className={`article-detail-wave ${activeArticle.tone}`}><Wave tone={activeArticle.tone}/></div><div className="article-body">{activeArticle.paragraphs.map(p=><p key={p}>{p}</p>)}</div>{activeArticle.source&&<SourceLink source={activeArticle.source}/>}<button className="button primary" onClick={()=>start()}>Подобрать действия по моему случаю</button></>}</SheetContent></Sheet>
 <Dialog open={!!draftType} onOpenChange={v=>{if(!v)setDraftType(null)}}><DialogContent className="draft-dialog"><DialogTitle className="dialog-title">{draftType==='bank'?'Черновик обращения в банк':'Черновик заявления в полицию'}</DialogTitle><DialogDescription>Замените поля в квадратных скобках. Текст можно изменить, скачать и обсудить со специалистом.</DialogDescription><textarea aria-label="Текст черновика" className="draft-text" maxLength={12000} value={draftText} onChange={e=>setDraftText(e.target.value)}/><div className="draft-actions"><button className="button primary" onClick={()=>download(`bereg-${draftType}.txt`,draftText)}><Download size={17}/>Скачать</button><button className="button secondary" onClick={()=>copy(draftText)}><Copy size={17}/>Копировать</button><button className="text-button" disabled={saveBusy} onClick={saveDraft}>{saveBusy?'Сохраняем…':'Сохранить в моём случае'}</button></div></DialogContent></Dialog>
 </div>
}
function ArticleCard({article:a,onClick}:{article:Article;onClick:()=>void}){return <button className="article-card" onClick={onClick}><div className={`article-art ${a.tone}`}><span className="article-tag">{a.tag}</span><Wave tone={a.tone}/><span className="article-art-icon">{a.tone==='blue'?<FileText/>:a.tone==='lime'?<HeartHandshake/>:<ShieldCheck/>}</span></div><div className="article-content"><h3>{a.title}</h3><p>{a.summary}</p><span className="card-link">Читать<Plus size={17}/></span></div></button>}
function EmptyState({title,text,action,onClick}:{title:string;text:string;action:string;onClick:()=>void}){return <div className="empty-state"><span className="empty-symbol"><Bookmark size={31}/></span><h2>{title}</h2><p>{text}</p><button className="button primary" onClick={onClick}>{action}</button></div>}
